#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  scripts/codexsdk_publish_sync_pr.sh --land-ref <branch> --target-ref <ref> --target-sha <sha> [options]

Options:
  --branch-prefix <prefix>  Sync branch prefix. Defaults to codex/sync-upstream.
  --candidate <path>        Candidate schema directory validated against the checked-in baseline.
  --remote <name>           Git remote to fetch and push. Defaults to origin.
  --skip-pr                 Push the sync branch but do not create or update a GitHub PR.

The script assumes HEAD is the committed sync change. It validates, rebases onto
the current remote landing ref, pushes a sync branch with force-with-lease when
updating an existing sync branch, then creates or updates a PR against the
landing ref.
EOF
}

branch_prefix="codex/sync-upstream"
candidate=""
land_ref=""
remote="origin"
skip_pr=false
target_ref=""
target_sha=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --branch-prefix)
      branch_prefix="$2"
      shift 2
      ;;
    --candidate)
      candidate="$2"
      shift 2
      ;;
    --land-ref)
      land_ref="$2"
      shift 2
      ;;
    --remote)
      remote="$2"
      shift 2
      ;;
    --skip-pr)
      skip_pr=true
      shift
      ;;
    --target-ref)
      target_ref="$2"
      shift 2
      ;;
    --target-sha)
      target_sha="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ -z "${land_ref}" || -z "${target_ref}" || -z "${target_sha}" ]]; then
  usage >&2
  exit 2
fi
land_ref="${land_ref#refs/heads/}"

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${repo_root}"

if ! git diff --quiet || ! git diff --cached --quiet; then
  echo "worktree must be clean before publishing a sync PR" >&2
  git status --short >&2
  exit 1
fi

write_output() {
  local name=$1
  local value=$2
  if [[ -n "${GITHUB_OUTPUT:-}" ]]; then
    printf '%s=%s\n' "${name}" "${value}" >> "${GITHUB_OUTPUT}"
  fi
}

validate_sync() {
  local args=(
    --target-sha "${target_sha}"
  )
  if [[ -n "${candidate}" ]]; then
    args+=(--candidate "${candidate}")
  fi
  scripts/codexsdk_validate_sync.sh "${args[@]}" || return 1
  if ! git diff --quiet || ! git diff --cached --quiet; then
    echo "validation changed the committed sync tree; commit validation changes before publishing" >&2
    git status --short >&2
    return 1
  fi
}

confirm_target_still_points_at_sha() {
  local resolved_sha
  resolved_sha="$(
    python3 scripts/codexsdk_resolve_upstream.py \
      --upstream-ref "${target_ref}" \
      --json |
      jq -r '.upstream_sha'
  )"
  if [[ "${resolved_sha}" != "${target_sha}" ]]; then
    echo "upstream target moved: ${target_ref} resolved to ${resolved_sha}, expected ${target_sha}" >&2
    return 1
  fi
}

fetch_landing_ref() {
  git fetch "${remote}" "refs/heads/${land_ref}:refs/remotes/${remote}/${land_ref}"
}

sync_branch_name() {
  python3 - "$branch_prefix" "$target_ref" "$target_sha" <<'PY'
import re
import sys

prefix, target_ref, target_sha = sys.argv[1:4]
name = re.sub(r"^refs/(heads|tags)/", "", target_ref) or target_sha[:12]
name = re.sub(r"[^A-Za-z0-9._-]+", "-", name).strip("-.")
if not name:
    name = target_sha[:12]
print(f"{prefix.rstrip('-/')}-{name[:80]}")
PY
}

push_sync_branch() {
  local sync_branch=$1
  local expected_remote=""

  if git fetch "${remote}" "refs/heads/${sync_branch}:refs/remotes/${remote}/${sync_branch}" 2>/dev/null; then
    expected_remote="$(git rev-parse "refs/remotes/${remote}/${sync_branch}")"
  fi

  if [[ -n "${expected_remote}" ]]; then
    git push \
      --force-with-lease="refs/heads/${sync_branch}:${expected_remote}" \
      "${remote}" "HEAD:refs/heads/${sync_branch}"
  else
    git push "${remote}" "HEAD:refs/heads/${sync_branch}"
  fi
}

create_or_update_pr() {
  local sync_branch=$1
  local sync_commit=$2
  local title
  local body_file
  local pr_number
  local pr_url

  if ! command -v gh >/dev/null 2>&1; then
    echo "gh is required to create or update the sync PR" >&2
    return 1
  fi

  title="Sync Codex protocol baseline to ${target_ref}"
  body_file="$(mktemp)"
  cat > "${body_file}" <<EOF
Automated upstream protocol sync.

- Upstream ref: \`${target_ref}\`
- Upstream commit: \`${target_sha}\`
- Sync commit: \`${sync_commit}\`
- Base branch: \`${land_ref}\`

This PR was generated by the upstream protocol auto-sync workflow. It should be merged only after the required \`Go\` check passes on this head commit.
EOF

  pr_number="$(
    gh pr list \
      --base "${land_ref}" \
      --head "${sync_branch}" \
      --state open \
      --json number \
      --jq '.[0].number // empty'
  )"

  if [[ -n "${pr_number}" ]]; then
    gh pr edit "${pr_number}" --title "${title}" --body-file "${body_file}" >/dev/null
    pr_url="$(gh pr view "${pr_number}" --json url --jq '.url')"
  else
    pr_url="$(
      gh pr create \
        --base "${land_ref}" \
        --head "${sync_branch}" \
        --title "${title}" \
        --body-file "${body_file}"
    )"
    pr_number="$(gh pr view "${pr_url}" --json number --jq '.number')"
  fi

  rm -f "${body_file}"
  write_output "pr_number" "${pr_number}"
  write_output "pr_url" "${pr_url}"
  printf '%s\n' "${pr_url}"
}

validate_sync
fetch_landing_ref
git rebase "${remote}/${land_ref}"
confirm_target_still_points_at_sha
validate_sync

sync_branch="$(sync_branch_name)"
sync_commit="$(git rev-parse HEAD)"
push_sync_branch "${sync_branch}"

write_output "sync_branch" "${sync_branch}"
write_output "sync_commit" "${sync_commit}"

if [[ "${skip_pr}" == true ]]; then
  exit 0
fi

create_or_update_pr "${sync_branch}" "${sync_commit}"
